### ISSUE TITLE
被豆瓣永久禁言

### ISSUE THREAD

**Issue by roaming-debug** [nekocode/doubanfm-py#6]
使用这款软件被永久禁言了！！！！！什么情况

**Comment by nekocode** [comment]
不太清楚。你确定和这个软件有关么？
如果确定和使用这个软件有关的话向你表示歉意，我会在 README 上补充说明避免其他人进坑 TwT

**Comment by roaming-debug** [comment]
我确定。那请问你是能够正常使用吗？

**Comment by nekocode** [comment]
我试试先

**Comment by nekocode** [comment]
![image](https://user-images.githubusercontent.com/4783781/66249411-92ac7680-e765-11e9-94f9-0802f8552af3.png)

确定了，确实会被永久禁言！万分抱歉，之前一直没问题，希望你能通过申诉解禁。

**Comment by roaming-debug** [comment]
但愿吧，现在国庆也没人工作值班，发邮件也没人回。当小白鼠了，心痛…

**Comment by nekocode** [comment]
再次表示抱歉... T_T

**Comment by roaming-debug** [comment]
没事，已解封😇
